/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSummaryBanner: typeof import('./src/components/business/AiSummaryBanner.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    CustomerCard: typeof import('./src/components/business/CustomerCard.vue')['default']
    FabButton: typeof import('./src/components/business/FabButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconSprite: typeof import('./src/components/common/IconSprite.vue')['default']
    NewCustomerCard: typeof import('./src/components/business/NewCustomerCard.vue')['default']
    OppBoardCard: typeof import('./src/components/business/OppBoardCard.vue')['default']
    ProductCard: typeof import('./src/components/business/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleCard: typeof import('./src/components/business/ScheduleCard.vue')['default']
    TabBar: typeof import('./src/components/common/TabBar.vue')['default']
    TaskCard: typeof import('./src/components/business/TaskCard.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
